services:
  postgres:
    image: postgres
    container_name: bowling_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - postgres_data_volume:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data_volume:
    driver: local